version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: proxy
    network_mode: 'host'
    restart: 'always'
    ports:
      - '80: 80'
    volumes: -./nginx/nginx. conf:/etc/nginx/nginx.conf

app-server:
  build: .
  container_name: app-server
  restart: always
  ports:
    - '3001:3001'
